version: "3.8"

networks:
  frontend:
    ipam:
      config:
        - subnet: 192.168.100.0/24

services:
  nginx:
    image: docker.io/wyveo/nginx-php-fpm:php81
    ports:
      - "80:80"
    container_name: nginx-php
    volumes: 
      - ./src:/var/www/html
      - ./nginx/default.conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      frontend:
        ipv4_address: 192.168.100.3

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./database/_data:/var/lib/mysql
    networks:
      frontend:
        ipv4_address: 192.168.100.4

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    container_name: pma
    restart: always
    ports:
      - "8000:80"
    networks:
      frontend:
        ipv4_address: 192.168.100.5